### PR TITLE
Some fixes in the spec.

### PR DESCRIPTION
**Pull request by BlueAndi**

### CODE REVIEW

**Review by grodansparadis — CHANGES_REQUESTED** [review]
This is autogenerated content that will be overwritten. Changes must be done in[ vscp-classes](https://github.com/grodansparadis/vscp-classes)

**Review by grodansparadis — CHANGES_REQUESTED** [review]
This is autogenerated content that will be overwritten. Changes must be done in[ vscp-classes](https://github.com/grodansparadis/vscp-classes)

**Review by grodansparadis — CHANGES_REQUESTED** [review]
This is autogenerated content that will be overwritten. Changes must be done in[ vscp-classes](https://github.com/grodansparadis/vscp-classes)

**Comment by BlueAndi** [comment]
*argh* I missed that. Pull request will follow.

**Comment by grodansparadis** [comment]
Thanks

**Pull request closed without merging**
